name: InventoryBinder
main: plugin.InventoryBinder
version: 1
commands:
   test:
      description: This is for testing purposes.
      usage: /<test>
   speed:
      description: This is for testing speed toggle.
      usage: /<speed>
   equip:
      description: This is for testing equip.
      usage: /<equip>   
